version: '3.9'

services:
  fastapi:
    build: ./ai_services  
    ports:
      - "8000:8000"

  node:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
      - todo
  todo:
    build: ./services/todo_service
    ports:
      - "3001:3001"
